stages:
  - build
  - deploy

build skoop:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - skoop
  script:
    - npm install
    - npm run build

deploy skoop:
  stage: deploy
  tags:
    - skoop
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - ls -a dist
    - cp -r dist/. ~/front-deployment

