stages:
  - build
  - deploy

build skoop:
  stage: build
  image: node:12-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - skoop
  script:
    - npm install
    - npm run build
  only:
    - 47-as-a-user-i-need-to-login-with-oauth
#    - develop
#    - master

deploy skoop:
  stage: deploy
  tags:
    - skoop
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r dist/skoop-front-end/. ~/front-deployment
  only:
    - 47-as-a-user-i-need-to-login-with-oauth
#    - develop
#    - master

